name: Tests

on:
  workflow_run:
    workflows: ["Build and Deploy"]
    types:
      - completed

jobs:
  lambda_function_test:
    name: Lambda Function Test
    runs-on: ubuntu-22.04
    if: github.event.workflow_run.conclusion == 'success'
    defaults:
      run:
        working-directory: ./infra
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install boto3 for unit test
        run: pip3 install boto3

      - name: Lambda Function unit test
        run: python3 src/test_main.py
